# 1. Data import and Data Cleaning

## 1.1 Repository in GitHub

In [17]:
# !rm -rf Eniac_project_part2                                       # only if there is an error
!git clone https://github.com/FlorianHast/Eniac_project_part2.git

!ls Eniac_project_part2/data/

# git add .
# git commit -m "Updated analysis"
# git push

fatal: destination path 'Eniac_project_part2' already exists and is not an empty directory.
brands.csv  orderlines.csv  orders.csv	products.csv

## 1.2 Import Data from GitHub

In [2]:
import pandas as pd

# orders.csv
orders_df = pd.read_csv('Eniac_project_part2/data/orders.csv')

# orderlines.csv
orderlines_df = pd.read_csv('Eniac_project_part2/data/orderlines.csv')

# products.csv
products_df = pd.read_csv('Eniac_project_part2/data/products.csv')

# brands.csv
brands_df = pd.read_csv('Eniac_project_part2/data/brands.csv')

## 1.3 Overview RawData

In [3]:
orders_df.head(10)

   order_id         created_date  total_paid      state
0    241319  2017-01-02 13:35:40       44.99  Cancelled
1    241423  2017-11-06 13:10:02      136.15  Completed
2    242832  2017-12-31 17:40:03       15.76  Completed
3    243330  2017-02-16 10:59:38       84.98  Completed
4    243784  2017-11-24 13:35:19      157.86  Cancelled
5    245275  2017-06-28 11:35:37      149.00  Completed
6    245595  2017-01-21 12:52:47      112.97  Completed
7    245851  2017-04-04 20:58:21       79.99    Pending
8    245941  2017-01-01 10:32:23      183.52  Completed
9    246018  2017-02-13 23:02:57      211.95  Completed

In [4]:
orderlines_df.head(10)

,id,id_order,product_id,product_quantity,sku,unit_price,date
0,1119109,299539,0,1,OTT0133,18.99,2017-01-01 00:07:19
1,1119110,299540,0,1,LGE0043,399.00,2017-01-01 00:19:45
2,1119111,299541,0,1,PAR0071,474.05,2017-01-01 00:20:57
3,1119112,299542,0,1,WDT0315,68.39,2017-01-01 00:51:40
4,1119113,299543,0,1,JBL0104,23.74,2017-01-01 01:06:38
5,1119114,295310,0,10,WDT0249,231.79,2017-01-01 01:14:27
6,1119115,299544,0,1,APP1582,1.137.99,2017-01-01 01:17:21
7,1119116,299545,0,1,OWC0100,47.49,2017-01-01 01:46:16
8,1119119,299546,0,1,IOT0014,18.99,2017-01-01 01:50:34
9,1119120,295347,0,1,APP0700,72.19,2017-01-01 01:54:11

In [5]:
products_df.head(10)

,sku,name,desc,price,promo_price,in_stock,type
0,RAI0007,Silver Rain Design mStand Support,Aluminum support compatible with all MacBook,59.99,499.899,1,8696
1,APP0023,Apple Mac Keyboard Keypad Spanish,USB ultrathin keyboard Apple Mac Spanish.,59,589.996,0,13855401
2,APP0025,Mighty Mouse Apple Mouse for Mac,mouse Apple USB cable.,59,569.898,0,1387
3,APP0072,Apple Dock to USB Cable iPhone and iPod white,IPhone dock and USB Cable Apple iPod.,25,229.997,0,1230
4,KIN0007,Mac Memory Kingston 2GB 667MHz DDR2 SO-DIMM,2GB RAM Mac mini and iMac (2006/07) MacBook Pr...,34.99,31.99,1,1364
5,APP0073,Apple Composite AV Cable iPhone and iPod white,IPhone and iPod AV Cable Dock to Composite Video.,45,420.003,0,1230
6,KIN0008,Mac Memory Kingston 1GB 667MHz DDR2 SO-DIMM,1GB RAM Mac mini and iMac (2006/07) MacBook Pr...,18.99,146.471,0,1364
7,KIN0009,Mac Memory Kingston 2GB 800MHz DDR2 SO-DIMM,2GB RAM iMac with Intel Core 2 Duo (Penryn).,36.99,274.694,0,1364
8,KIN0001-2,Mac memory Kingston 4GB (2x2GB) 667MHz DDR2 SO...,RAM 4GB (2x2GB) Mac mini and iMac (2006/07) Ma...,74,669.904,0,1364
9,APP0100,Apple Adapter Mini Display Port to VGA,Adapter Mini Display Port to VGA MacBook and M...,35,330.003,0,1325

In [6]:
brands_df.head(10)

  short        long
0   8MO   8Mobility
1   ACM        Acme
2   ADN      Adonit
3   AII       Aiino
4   AKI      Akitio
5   ALL   Allocacoc
6   AP2       Apple
7   APP       Apple
8   BAN  Band&Strap
9   BEA       Beats

# 2. Data Cleaning

## 2.1 orders.csv

In [12]:
orders_df
# pd.to_datetime(orders_df)

        order_id         created_date  total_paid            state
0         241319  2017-01-02 13:35:40       44.99        Cancelled
1         241423  2017-11-06 13:10:02      136.15        Completed
2         242832  2017-12-31 17:40:03       15.76        Completed
3         243330  2017-02-16 10:59:38       84.98        Completed
4         243784  2017-11-24 13:35:19      157.86        Cancelled
...          ...                  ...         ...              ...
226904    527397  2018-03-14 13:56:38       42.99      Place Order
226905    527398  2018-03-14 13:57:25       42.99  Shopping Basket
226906    527399  2018-03-14 13:57:34      141.58  Shopping Basket
226907    527400  2018-03-14 13:57:41       19.98  Shopping Basket
226908    527401  2018-03-14 13:58:36       18.98      Place Order

[226909 rows x 4 columns]