# 1. Setup GitHub and Data import

## Team Best Practice (Data Science)

<details>
<summary>Click to expand: Team Best Practice</summary>

**Recommended setup**

### 👥 Each team member

Works on their own branch:

```bash
git checkout -b florian-analysis
```

---

### 🚀 Push your work

```bash
git push origin florian-analysis
```

---

### 🔀 Merge workflow (on GitHub)

- Open a Pull Request (PR)
- Team reviews changes
- Merge into `main`

👉 This keeps the project clean and avoids conflicts.

---

## ⚠️ Important for Colab

Colab is **not a version control system**:

- Changes are only stored in the current session  
- If the runtime restarts → work is lost  

---

## 💡 Therefore always:

> **Colab + GitHub = proper saving & version control**

## 1.1 Clone Repository in GitHub

In [37]:
# only if there is an error
!rm -rf Eniac_project_part2

# clone GitHub repository
!git clone https://github.com/FlorianHast/Eniac_project_part2.git

# enter repository
%cd Eniac_project_part2

# update local main
!git checkout main
!git pull

# create personal branch
!git checkout -b florian-cleaning

# inspect data folder
!ls data/

Cloning into 'Eniac_project_part2'...
remote: Enumerating objects: 99, done.
remote: Counting objects: 100% (99/99), done.
remote: Compressing objects: 100% (86/86), done.
remote: Total 99 (delta 49), reused 14 (delta 8), pack-reused 0 (from 0)
Receiving objects: 100% (99/99), 6.11 MiB | 4.38 MiB/s, done.
Resolving deltas: 100% (49/49), done.
/content/Eniac_project_part2/Eniac_project_part2
Already on 'main'
Your branch is up to date with 'origin/main'.
Already up to date.
Switched to a new branch 'florian-cleaning'
brands.csv  orderlines.csv  orders.csv	products.csv

In [40]:
!ls data/

brands.csv  orderlines.csv  orders.csv	products.csv

## 1.2 Push to GitHub

In [ ]:
# After you are doing your work
# stage changes
!git add .

# commit
!git commit -m "Colab update"                                       # your message = title of the changes made

# safety check
!git status
!git branch                                                         # do make sure you are on your branch

# Then push: Push your work, Colab is only temporary!
!git push -u origin florian-cleaning                                # first push on your branch
# !git push                                                         # once you defined your branch in the push statement above, you can write only push as well

[your-name-feature 04b1f96] Colab update
 1 file changed, 1 insertion(+), 1 deletion(-)
On branch your-name-feature
nothing to commit, working tree clean
  florian-cleaning
  main
* your-name-feature
Branch 'florian-cleaning' set up to track remote branch 'florian-cleaning' from 'origin'.
Everything up-to-date

## 1.3 Import Data from GitHub

In [74]:
import pandas as pd

# if something goes wrong with your DataFrame you can reset them here by running this code block!

# orders.csv
orders_df = pd.read_csv('data/orders.csv')

# orderlines.csv
orderlines_df = pd.read_csv('data/orderlines.csv')

# products.csv
products_df = pd.read_csv('data/products.csv')

# brands.csv
brands_df = pd.read_csv('data/brands.csv')

## 1.3 Overview RawData

In [42]:
orders_df.head(10)

   order_id         created_date  total_paid      state
0    241319  2017-01-02 13:35:40       44.99  Cancelled
1    241423  2017-11-06 13:10:02      136.15  Completed
2    242832  2017-12-31 17:40:03       15.76  Completed
3    243330  2017-02-16 10:59:38       84.98  Completed
4    243784  2017-11-24 13:35:19      157.86  Cancelled
5    245275  2017-06-28 11:35:37      149.00  Completed
6    245595  2017-01-21 12:52:47      112.97  Completed
7    245851  2017-04-04 20:58:21       79.99    Pending
8    245941  2017-01-01 10:32:23      183.52  Completed
9    246018  2017-02-13 23:02:57      211.95  Completed

In [43]:
orderlines_df.head(10)

,id,id_order,product_id,product_quantity,sku,unit_price,date
0,1119109,299539,0,1,OTT0133,18.99,2017-01-01 00:07:19
1,1119110,299540,0,1,LGE0043,399.00,2017-01-01 00:19:45
2,1119111,299541,0,1,PAR0071,474.05,2017-01-01 00:20:57
3,1119112,299542,0,1,WDT0315,68.39,2017-01-01 00:51:40
4,1119113,299543,0,1,JBL0104,23.74,2017-01-01 01:06:38
5,1119114,295310,0,10,WDT0249,231.79,2017-01-01 01:14:27
6,1119115,299544,0,1,APP1582,1.137.99,2017-01-01 01:17:21
7,1119116,299545,0,1,OWC0100,47.49,2017-01-01 01:46:16
8,1119119,299546,0,1,IOT0014,18.99,2017-01-01 01:50:34
9,1119120,295347,0,1,APP0700,72.19,2017-01-01 01:54:11

In [44]:
products_df.head(10)

,sku,name,desc,price,promo_price,in_stock,type
0,RAI0007,Silver Rain Design mStand Support,Aluminum support compatible with all MacBook,59.99,499.899,1,8696
1,APP0023,Apple Mac Keyboard Keypad Spanish,USB ultrathin keyboard Apple Mac Spanish.,59,589.996,0,13855401
2,APP0025,Mighty Mouse Apple Mouse for Mac,mouse Apple USB cable.,59,569.898,0,1387
3,APP0072,Apple Dock to USB Cable iPhone and iPod white,IPhone dock and USB Cable Apple iPod.,25,229.997,0,1230
4,KIN0007,Mac Memory Kingston 2GB 667MHz DDR2 SO-DIMM,2GB RAM Mac mini and iMac (2006/07) MacBook Pr...,34.99,31.99,1,1364
5,APP0073,Apple Composite AV Cable iPhone and iPod white,IPhone and iPod AV Cable Dock to Composite Video.,45,420.003,0,1230
6,KIN0008,Mac Memory Kingston 1GB 667MHz DDR2 SO-DIMM,1GB RAM Mac mini and iMac (2006/07) MacBook Pr...,18.99,146.471,0,1364
7,KIN0009,Mac Memory Kingston 2GB 800MHz DDR2 SO-DIMM,2GB RAM iMac with Intel Core 2 Duo (Penryn).,36.99,274.694,0,1364
8,KIN0001-2,Mac memory Kingston 4GB (2x2GB) 667MHz DDR2 SO...,RAM 4GB (2x2GB) Mac mini and iMac (2006/07) Ma...,74,669.904,0,1364
9,APP0100,Apple Adapter Mini Display Port to VGA,Adapter Mini Display Port to VGA MacBook and M...,35,330.003,0,1325

In [45]:
brands_df.head(10)

  short        long
0   8MO   8Mobility
1   ACM        Acme
2   ADN      Adonit
3   AII       Aiino
4   AKI      Akitio
5   ALL   Allocacoc
6   AP2       Apple
7   APP       Apple
8   BAN  Band&Strap
9   BEA       Beats

# 2. Data Cleaning

## 2.1 orders.csv

In [46]:
# orders_df.info()

# # drop the rows with NaN values in 'total_paid':
# orders_df = orders_df.dropna(subset=['total_paid'])

# # check if rows with NaN values actually got dropped
# NaN_remaining = orders_df['total_paid'].isna().sum()

# print(f"There are {NaN_remaining} 'NaN' values remaining")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 226909 entries, 0 to 226908
Data columns (total 4 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   order_id      226909 non-null  int64
 1   created_date  226909 non-null  object
 2   total_paid    226904 non-null  float64
 3   state         226909 non-null  object
dtypes: float64(1), int64(1), object(2)
memory usage: 6.9+ MB
There are 0 'NaN' values remaining

In [47]:
# check for duplicates
# orders_df.duplicated().sum()

np.int64(0)

In [48]:
# # format 'create_date' as datetime
# orders_df['created_date'] = pd.to_datetime(orders_df['created_date'])

# orders_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 226904 entries, 0 to 226908
Data columns (total 4 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   order_id      226904 non-null  int64
 1   created_date  226904 non-null  datetime64[ns]
 2   total_paid    226904 non-null  float64
 3   state         226904 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(1), object(1)
memory usage: 8.7+ MB

In [49]:
# # check for range in 'total paid'
# orders_df.sort_values(['total_paid'])

# # check for range in 'created_date'
# orders_df.sort_values(['created_date'])

# # check if there are more states than the 5 described in LMS
# orders_df['state'].unique()

array(['Cancelled', 'Completed', 'Pending', 'Shopping Basket',
       'Place Order'], dtype=object)

Problem with the data: <br>
Orders.csv contains<br>
* orders with a 'total_paid' of 0,- € with 'place order' state (might be due to discounts?)<br>
* and orders with +200.000,- € paid(!) with 'Shopping Basket' state (if in basket, it´s not paid yet...)

## 2.2 orderlines.csv

In [92]:
# drop the outdated, unused 'product_id'
orderlines_df = orderlines_df.drop(['product_id'], axis=1)

In [93]:
# format 'date' as datetime
orderlines_df['date'] = pd.to_datetime(orderlines_df['date'])

In [95]:
# # replace '.' with '' if it is not a decimal point
orderlines_df['unit_price'] = (orderlines_df['unit_price'].str.replace(r'\.(?=.*\.)', '', regex=True))

# # format 'unit_price' as float
orderlines_df['unit_price'] = orderlines_df['unit_price'].astype(float)

# # check if there are commas -> NO commas!
# # orderlines_df['unit_price'].str.contains(',').sum()

In [96]:
orderlines_df.sort_values(['unit_price'], ascending=False)

,id,id_order,product_quantity,sku,unit_price,date,brand_code
36979,1197439,331780,1,NEA0009,159989.83,2017-03-03 22:29:21,NEA
38317,1200059,332976,6,LAC0223,15349.00,2017-03-07 15:51:14,LAC
282442,1632863,520029,1,APP2660,14725.00,2018-03-02 11:57:52,APP
241912,1567694,491691,1,APP2660,14580.00,2018-01-18 14:40:05,APP
232077,1551059,487192,1,APP2660,14580.00,2018-01-10 00:05:59,APP
...,...,...,...,...,...,...,...
195578,1486720,458984,1,QNA0146,0.00,2017-12-10 16:00:35,QNA
58598,1236323,350095,1,LIBRO,0.00,2017-04-26 18:33:26,LIB
58638,1236404,350138,1,LIBRO,0.00,2017-04-26 20:47:13,LIB
58464,1236111,350006,1,LIBRO,0.00,2017-04-26 15:15:53,LIB
77008,1268645,365886,1,APP1465,-119.00,2017-06-15 12:48:54,APP

Problem with the data: <br>
Orderlines.csv contains<br>
* orders with a 'unit_price' of 0,- € and even a negative value (-119,-, might be due to discounts or typo?)<br>
* and unit_price over 999.99 € are sorted in the 1, 2, ... and so forth, because<br>
  * there´s a issue with the thousands delimiter (e.g. 1.137.99)<br>
  * datatype as string (maybe replace all ‘.’ (except decimal) with ‘’ (nothing) <br>
  * are there also commas in the mix? -> NO
* highest values in unit_price over 10000.- €, max is even over 150000.- €!

## 2.3 products.csv

In [55]:
# reset DataFrame
# # products.csv
# products_df = pd.read_csv('data/products.csv')
# products_df['price'].sort_values().head(5)

14756    1.090.004
12316    1.099.043
1459     1.169.795
17392    1.199.897
11102    1.199.897
Name: price, dtype: object

In [56]:
# # replace '.' with '' if it is not a decimal point
# products_df['price'] = (products_df['price'].str.replace(r'\.(?=.*\.)', '', regex=True))
# products_df['promo_price'] = (products_df['promo_price'].str.replace(r'\.(?=.*\.)', '', regex=True))

# # format 'price' as float
# products_df['price'] = products_df['price'].astype(float)
# products_df['promo_price'] = products_df['promo_price'].astype(float)

# # check if there are commas -> NO commas!
# # products_df['price'].str.contains(',').sum()

# products_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19326 entries, 0 to 19325
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sku          19326 non-null  object
 1   name         19326 non-null  object
 2   desc         19319 non-null  object
 3   price        19280 non-null  float64
 4   promo_price  19326 non-null  float64
 5   in_stock     19326 non-null  int64
 6   type         19276 non-null  object
dtypes: float64(2), int64(1), object(4)
memory usage: 1.0+ MB

In [57]:
# products_df.sort_values(['price'], ascending=False)

,sku,name,desc,price,promo_price,in_stock,type
16608,APP2333,"Apple MacBook Pro 15 ""Core i7 Touch Bar 31GHz ...",New MacBook Pro 15-inch Core i7 Touch Bar 31Gh...,352559.394,35255.939,0,"1,02E+12"
16824,APP2299,"Apple MacBook Pro 13 ""Core i7 Touch Bar 35GHz ...",New MacBook Pro 13 inch Touch Bar 35 GHz Core ...,336559.443,33655.944,0,"1,02E+12"
16834,APP2307,"Apple MacBook Pro 13 ""Core i5 Touch Bar 33GHz ...",New MacBook Pro 13-inch Core i5 Touch Bar 33 G...,336559.443,33655.944,0,"1,02E+12"
16812,APP2296,"Apple MacBook Pro 13 ""Core i5 Touch Bar 33GHz ...",New MacBook Pro 13-inch Core i5 Touch Bar 33 G...,336559.443,33655.944,0,"1,02E+12"
16836,APP2310,"Apple MacBook Pro 13 ""Core i7 Touch Bar 35GHz ...",New MacBook Pro 13 inch Touch Bar 35 GHz Core ...,336559.443,33655.944,0,"1,02E+12"
...,...,...,...,...,...,...,...
12098,CEL0050,Laser Case Celly iPhone 6 / 6S Plus Silver Clear,Protective Case for iPhone 6 Plus and 6s Plus,NaN,149.895,0,11865403
12100,CEL0037,Celly Frost Cover for iPhone 6 / 6S Black,Ultra Thin Case for iPhone 6 and 6s,NaN,99.898,0,11865403
12238,CEL0027,Celly Frost Cover for iPhone 6 / 6S White,Flexible plastic shell for iPhone 6 / 6S,NaN,89.903,0,11865403
12242,CEL0039,Celly Frost Cover for iPhone 6 / 6S Amarillo,Ultra Thin Case for iPhone 6 and 6s,NaN,89.903,0,11865403
12947,CEL0034-A,(Open) Celly iPhone 6S Plus Housing Frost White,Ultra Thin Case for iPhone 6 and 6s Plus,NaN,74.893,0,1298

## 2.4 brands.csv

In [58]:
brands_df

    short       long
0     8MO  8Mobility
1     ACM       Acme
2     ADN     Adonit
3     AII      Aiino
4     AKI     Akitio
..    ...        ...
182   XOO     Xoopar
183   XRI     X-Rite
184   XTO      Xtorm
185   ZAG   ZaggKeys
186   ZEP       Zepp

[187 rows x 2 columns]

# Joined DataFrame

In [75]:
orderlines_df['brand_code'] = orderlines_df['sku'].str[:3]

merged_df = (orderlines_df.merge(orders_df, left_on='id_order', right_on='order_id', how='inner')
              .merge(products_df, on='sku', how='inner')
              .merge(brands_df, left_on = 'brand_code', right_on='short', how='inner')
              )


merged_df = merged_df[['id', 'order_id', 'sku', 'name', 'desc' , 'long', 'product_quantity', 'unit_price', 'price', 'promo_price', 'total_paid', 'state', 'in_stock', 'type', 'date', 'created_date']]


merged_df = merged_df.drop_duplicates()
# merged_df.duplicated().sum()


# merged_df.loc[merged_df['unit_price'].str.startswith('1')].sort_values('unit_price').head(20)

merged_df

,id,order_id,sku,name,desc,long,product_quantity,unit_price,price,promo_price,total_paid,state,in_stock,type,date,created_date
0,1119109,299539,OTT0133,Otterbox iPhone Case Symmetry 2.0 SE / 5s / 5 ...,resistant cover and thin beveled edges for iPh...,Otterbox,1,18.99,34.99,199.904,18.99,Shopping Basket,0,11865403,2017-01-01 00:07:19,2017-01-01 00:07:19
1,1119110,299540,LGE0043,"27UD58-B LG Monitor 27 ""4K UHD DisplayPort",Monitor for gamers and multimedia professional...,LG,1,399.00,429,3.989.999,399.00,Shopping Basket,0,1296,2017-01-01 00:19:45,2017-01-01 00:19:45
2,1119111,299541,PAR0071,Parrot Bebop 2 White + Command FLYPAD and FPV ...,cuadricóptero wireless remote control with 25 ...,Parrot,1,474.05,699,5.689.989,474.05,Shopping Basket,0,11905404,2017-01-01 00:20:57,2017-01-01 00:20:57
3,1119112,299542,WDT0315,"Blue WD 2TB Hard Drive 35 ""Mac and PC",Internal Hard Drive Western Digital 2TB 3.5-in...,Western Digital,1,68.39,79,639.945,68.39,Shopping Basket,0,12655397,2017-01-01 00:51:40,2017-01-01 00:51:40
4,1119113,299543,JBL0104,Gray Bluetooth Speaker JBL GO,Compact Bluetooth Handsfree for iPhone iPad an...,JBL,1,23.74,29.9,27.99,23.74,Shopping Basket,1,5398,2017-01-01 01:06:38,2017-01-01 01:06:38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
377719,1650199,527398,JBL0122,JBL T450 BT Bluetooth Headset Black,Wireless headphones with folding design with 1...,JBL,1,42.99,49.95,429.901,42.99,Shopping Basket,1,5384,2018-03-14 13:57:25,2018-03-14 13:57:25
377720,1650200,527399,PAC0653,Samsung SSD 850 expansion kit EVO 250GB + Data...,SSD upgrade kit 2008-2010 250 GB MacBook and M...,Pack,1,141.58,215.98,1.415.845,141.58,Shopping Basket,1,1433,2018-03-14 13:57:34,2018-03-14 13:57:34
377721,1650201,527400,APP0698,Apple Lightning Cable Connector to USB 1m Whit...,Apple Lightning USB Cable 1 meter to charge an...,Apple,2,9.99,25,99.898,19.98,Shopping Basket,1,1230,2018-03-14 13:57:41,2018-03-14 13:57:41
377722,1650202,527388,BEZ0204,"Be.ez LArobe Case Mix Macbook 12 ""Green",Macbook thin sheath 12 inches.,Be.ez,1,19.99,29.99,199.904,34.98,Shopping Basket,0,13835403,2018-03-14 13:58:01,2018-03-14 13:51:59
377723,1650203,527401,APP0927,EarPods Apple Headphones with Remote and Mic (...,EarPods headphones Apple iPhone iPad and iPod ...,Apple,1,13.99,35,13.99,18.98,Place Order,1,5384,2018-03-14 13:58:36,2018-03-14 13:58:36

In [101]:
# # replace '.' with '' if it is not a decimal point
merged_df['unit_price'] = (merged_df['unit_price'].str.replace(r'\.(?=.*\.)', '', regex=True))

# # format 'unit_price' as float
merged_df['unit_price'] = merged_df['unit_price'].astype(float)

In [111]:
merged_df.sort_values('unit_price').tail(20)

,id,order_id,sku,name,desc,long,product_quantity,unit_price,price,promo_price,total_paid,state,in_stock,type,date,created_date
357158,1626821,517295,APP2648,"Apple iMac Pro 27 ""18-core Intel Xeon W 23GHz ...",Pro iMac 27 inch screen Retina 5K and Intel Xe...,Apple,1,12419.00,12939,121.630.047,37783.03,Shopping Basket,0,118692158,2018-02-25 20:43:51,2018-02-25 20:43:51
338233,1599098,505474,APP2648,"Apple iMac Pro 27 ""18-core Intel Xeon W 23GHz ...",Pro iMac 27 inch screen Retina 5K and Intel Xe...,Apple,1,12428.03,12939,121.630.047,12435.02,Place Order,0,118692158,2018-02-04 15:01:47,2018-02-04 15:01:47
337489,1598401,505235,APP2648,"Apple iMac Pro 27 ""18-core Intel Xeon W 23GHz ...",Pro iMac 27 inch screen Retina 5K and Intel Xe...,Apple,1,12428.03,12939,121.630.047,12428.03,Cancelled,0,118692158,2018-02-03 23:04:55,2018-02-03 23:06:40
337414,1598287,505187,APP2648,"Apple iMac Pro 27 ""18-core Intel Xeon W 23GHz ...",Pro iMac 27 inch screen Retina 5K and Intel Xe...,Apple,1,12428.03,12939,121.630.047,12428.03,Place Order,0,118692158,2018-02-03 20:21:15,2018-02-03 20:21:15
356252,1625977,516941,APP2659,"Apple iMac Pro 27 ""14-core Intel Xeon W 25GHz ...",Pro iMac 27 inch screen Retina 5K and Intel Xe...,Apple,1,13799.00,14379,135.160.049,13799.00,Shopping Basket,0,118692158,2018-02-24 20:48:48,2018-02-24 20:48:48
108589,1244301,354084,LAC0223,12big LaCie Hard Disk 120TB RAID Thunderbolt 3...,12 120TB hard drive bays with RAID 5 two ports...,LaCie,4,14099.00,9799,78.999.944,56396.00,Shopping Basket,0,11935397,2017-05-09 09:04:18,2017-05-09 09:04:18
106134,1241776,352790,LAC0223,12big LaCie Hard Disk 120TB RAID Thunderbolt 3...,12 120TB hard drive bays with RAID 5 two ports...,LaCie,3,14099.00,9799,78.999.944,48684.97,Shopping Basket,0,11935397,2017-05-04 18:59:32,2017-05-04 18:59:32
366380,1639082,522749,APP2660,"Apple iMac Pro 27 ""18-core Intel Xeon W 23GHz ...",Pro iMac 27 inch screen Retina 5K and Intel Xe...,Apple,1,14419.00,15339,144.190.049,14419.00,Shopping Basket,0,118692158,2018-03-07 13:48:15,2018-03-07 13:48:15
366547,1639306,522845,APP2660,"Apple iMac Pro 27 ""18-core Intel Xeon W 23GHz ...",Pro iMac 27 inch screen Retina 5K and Intel Xe...,Apple,1,14419.00,15339,144.190.049,14419.00,Shopping Basket,0,118692158,2018-03-07 16:40:22,2018-03-07 16:40:22
329833,1588363,501413,APP2660,"Apple iMac Pro 27 ""18-core Intel Xeon W 23GHz ...",Pro iMac 27 inch screen Retina 5K and Intel Xe...,Apple,1,14580.00,15339,144.190.049,16948.98,Shopping Basket,0,118692158,2018-01-29 18:58:03,2018-01-29 18:57:53
314924,1567694,491691,APP2660,"Apple iMac Pro 27 ""18-core Intel Xeon W 23GHz ...",Pro iMac 27 inch screen Retina 5K and Intel Xe...,Apple,1,14580.00,15339,144.190.049,14586.99,Cancelled,0,118692158,2018-01-18 14:40:05,2018-01-19 15:45:14
327666,1585660,500546,APP2660,"Apple iMac Pro 27 ""18-core Intel Xeon W 23GHz ...",Pro iMac 27 inch screen Retina 5K and Intel Xe...,Apple,1,14580.00,15339,144.190.049,35930.10,Shopping Basket,0,118692158,2018-01-29 01:55:02,2018-01-29 01:55:02
304000,1551059,487192,APP2660,"Apple iMac Pro 27 ""18-core Intel Xeon W 23GHz ...",Pro iMac 27 inch screen Retina 5K and Intel Xe...,Apple,1,14580.00,15339,144.190.049,14580.00,Shopping Basket,0,118692158,2018-01-10 00:05:59,2018-01-10 00:05:59
321931,1577659,497375,APP2660,"Apple iMac Pro 27 ""18-core Intel Xeon W 23GHz ...",Pro iMac 27 inch screen Retina 5K and Intel Xe...,Apple,1,14580.00,15339,144.190.049,14580.00,Shopping Basket,0,118692158,2018-01-23 23:55:41,2018-01-23 23:55:41
307259,1555558,488935,APP2660,"Apple iMac Pro 27 ""18-core Intel Xeon W 23GHz ...",Pro iMac 27 inch screen Retina 5K and Intel Xe...,Apple,4,14580.00,15339,144.190.049,121521.85,Shopping Basket,0,118692158,2018-01-11 21:11:34,2018-01-11 21:11:34
303937,1551007,487164,APP2660,"Apple iMac Pro 27 ""18-core Intel Xeon W 23GHz ...",Pro iMac 27 inch screen Retina 5K and Intel Xe...,Apple,1,14580.00,15339,144.190.049,14580.00,Shopping Basket,0,118692158,2018-01-09 23:33:16,2018-01-09 23:33:16
329478,1587927,501275,APP2660,"Apple iMac Pro 27 ""18-core Intel Xeon W 23GHz ...",Pro iMac 27 inch screen Retina 5K and Intel Xe...,Apple,1,14580.00,15339,144.190.049,14580.00,Shopping Basket,0,118692158,2018-01-29 17:18:55,2018-01-29 17:18:55
360783,1632863,520029,APP2660,"Apple iMac Pro 27 ""18-core Intel Xeon W 23GHz ...",Pro iMac 27 inch screen Retina 5K and Intel Xe...,Apple,1,14725.00,15339,144.190.049,14731.99,Place Order,0,118692158,2018-03-02 11:57:52,2018-03-02 11:57:52
64865,1200059,332976,LAC0223,12big LaCie Hard Disk 120TB RAID Thunderbolt 3...,12 120TB hard drive bays with RAID 5 two ports...,LaCie,6,15349.00,9799,78.999.944,92094.00,Shopping Basket,0,11935397,2017-03-07 15:51:14,2017-03-07 15:51:14
62480,1197439,331780,NEA0009,Netatmo home thermostat for iPhone and iPad,Thermostat iPhone iPad wifi Mac design Stark.,Netatmo,1,159989.83,179,174.989,159989.83,Shopping Basket,0,11905404,2017-03-03 22:29:21,2017-03-03 22:29:21